name: Update Repository

on:
  push:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: 'rockylinux/rockylinux:9'
      env:
        LANG: ja_JP.UTF-8
    steps:
      - name: Locale ja_JP.UTF-8
        run: dnf install -y glibc-locale-source glibc-langpack-en glibc-langpack-ja

      - name: Install packaging dependencies for Rocky 9
        run: dnf -y install git createrepo gnupg2 rpm-sign

      - name: Configure GPG
        run: |
          # echo "GPG_TTY=${TTY}" >> $GITHUB_ENV
          eval $(gpg-agent --daemon --allow-preset-passphrase --default-cache-ttl 43200)
          tee ~/.gnupg/gpg-agent.conf << 'EOF' > /dev/null
          default-cache-ttl 43200
          allow-preset-passphrase
          EOF
          gpg-connect-agent 'RELOADAGENT' /bye
          gpg-connect-agent "PRESET_PASSPHRASE ${GPG_KEYGRIP} -1 $(echo -n "${GPG_PASSPHRASE}" | hexdump -v -e '/1 "%02X"')" /bye
          echo -n "$GPG_SIGNING_KEY" | gpg --batch --import
          FINGERPRINT=$(gpg --list-secret-keys --with-colons | grep "^fpr" | cut -d: -f10 | head -1)
          echo "GPG_FINGERPRINT=${FINGERPRINT}" >> $GITHUB_ENV
          echo "$FINGERPRINT:6:" | gpg --import-ownertrust
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEYGRIP: ${{ secrets.GPG_KEYGRIP }}

      - name: Create rpm-build environment.
        run: |
          echo '%debug_package %{nil}' >> ~/.rpmmacros

      - name: Checkout repos
        uses: actions/checkout@v3
        with:
          path: repos

      - name: Add sign to rpm
        run: |
          cd ${GITHUB_WORKSPACE}/repos
          # rpm command don't aware gpg-agent.
          rpm \
          --define "_signature gpg" \
          --define "_gpg_name Tsuyamax <3974168+tsuyamax@users.noreply.github.com>" \
          --define "_gpg_sign_cmd_extra_args --batch --pinentry-mode loopback --passphrase ${GPG_PASSPHRASE}" \
          --addsign rpm/{7,8,9}/x86_64/Packages/*.rpm
          gpg --export --armor > rpm/RPM-GPG-KEY-TSUYAMAX
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Update repodata
        run: |
          cd ${GITHUB_WORKSPACE}/repos
          mkdir -p rpm/{7,8,9}/x86_64/
          createrepo --database rpm/7/x86_64/
          createrepo --database rpm/8/x86_64/
          createrepo --database rpm/9/x86_64/

      - name: Delete gpg key
        run: |
          gpg --batch --delete-secret-keys $GPG_FINGERPRINT
          gpg-connect-agent 'KILLAGENT' /bye
        env:
          GPG_FINGERPRINT: ${{ secrets.GPG_FINGERPRINT }}

      - name: Commit updates
        run: |
          cd ${GITHUB_WORKSPACE}/repos
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Update rpm metadata"
          fi
  
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          directory: ${{ github.workspace }}/repos
