name: Update Repository

on:
  push:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: 'rockylinux/rockylinux:8'
      env:
        LANG: ja_JP.UTF-8
    steps:
      - name: Locale ja_JP.UTF-8
        run: dnf install -y glibc-locale-source glibc-langpack-en glibc-langpack-ja

      - name: Install packaging dependencies for Rocky 8
        run: dnf -y install git createrepo

      - name: Checkout repos
        uses: actions/checkout@v3
        with:
          path: repos

      - name: Update repodata
        run: |
          cd ${GITHUB_WORKSPACE}/repos
          createrepo --database rpm/7/x86_64/
          createrepo --database rpm/8/x86_64/

      - name: Commit updates
        run: |
          cd ${GITHUB_WORKSPACE}/repos
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Update rpm metadata"
          fi
  
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          directory: ${{ github.workspace }}/repos
